export const STAFF_REQMT_LIST_REQUEST = "STAFF_REQMT_LIST_REQUEST";
export const STAFF_REQMT_LIST_SUCCESS = "STAFF_REQMT_LIST_SUCCESS";
export const STAFF_REQMT_LIST_FAILURE = "STAFF_REQMT_LIST_FAILURE";
export const STAFF_REQMT_LIST_RESET = "STAFF_REQMT_LIST_RESET";
