export const LIST_COLLECTION_REQUEST = "LIST_COLLECTION_REQUEST";
export const LIST_COLLECTION_SUCCESS = "LIST_COLLECTION_SUCCESS";
export const LIST_COLLECTION_FAILURE = "LIST_COLLECTION_FAILURE";
export const LIST_COLLECTION_RESET = "LIST_COLLECTION_RESET";
