export const EMAIL_SERVICE_REQUEST = "EMAIL_SERVICE_REQUEST";
export const EMAIL_SERVICE_SUCCESS = "EMAIL_SERVICE_SUCCESS";
export const EMAIL_SERVICE_FAILURE = "EMAIL_SERVICE_FAILURE";
export const EMAIL_SERVICE_RESET = "EMAIL_SERVICE_RESET";
